### ISSUE TITLE
Bots in the "recently updated" search results.

### ISSUE THREAD

**Issue by kustomzone** [electron/download-stats#1]
Hey zeke. 

I'm sure it's nice for some to have hourly updates, but is there some way that bots that update their repos don't, by doing so, also keep those repos at the top of "recently updated" search results.
I suspect this will become an increasing problem as more bots use API updating methods.
Perhaps less than (or =) 24 hour use of the API would indicate a bot and the "recently updated" flag could be left un-ticked in the search index.

(eg Automation TLDR ;)

**Comment by zeke** [comment]
Hey @kustomzone. Which "recently updated" search results are you referring to?

**Comment by kustomzone** [comment]
Well any search term really. Besides following "trending" (daily stars) some of us search keywords (Electron, etc) for new updates generally, but these keyword searches will lose some their value if more of the first results become a collection of repos updated by bots. Some keyword searches move slowly, while others are in heavy use, so striking a balance might be needed. Not all API use will be bots, but regular hourly or daily updating would be a good indicator.

**Comment by zeke** [comment]
Sorry but I'm still not really sure what you're talking about. GitHub search? Google search? npm search?

**Comment by kustomzone** [comment]
![recentlyupdated](https://cloud.githubusercontent.com/assets/2006565/22512129/d97cb38c-e8fc-11e6-9ae0-b6bf644a7348.jpg)

**Comment by zeke** [comment]
I see. I don't have much control over that... do you think it would help if I changed the update interval to daily instead of hourly?

**Comment by kustomzone** [comment]
Besides implementing a convoluted check to look for bot-like activity (using the API) it could be voluntarily handled with the new "Topics" tags ("Manage Topics" feature) by adding "gitbot" or "autobot" to our project. Then the search could exclude these from the results, or limit their frequency.

I know you don't have control over this, but thought it needs so be discussed as bots are fairly new.
Yeah, daily might be okay in this case. Can see if anyone else has a suggestion for projects that need higher frequency updates.
